#!/usr/bin/env bash
# Configure Nginx with custom  header
sudo apt update -y
sudo apt install -y niginx

host=$(hostname)
sed -i "/server_name _;/a \    add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
sudo nginx -s reload
