#!/usr/bin/env bash
# Configure nginx to redirect '/redirect_me' to Google using 301

sudo apt update -y
sudo apt install -y nginx

echo "Holberton School" > /var/www/html/index.html

cat > /etc/nginx/sites-available/default <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    location / {
        try_files \$uri \$uri/ =404;
    }

    location /redirect_me {
        return 301 https://www.google.com/;
    }
}
EOF

sudo service nginx restart
