#!/usr/bin/env bash
# Configure nginx to redirect '/redirect_me' to Google using 301

apt update -y
apt install -y nginx

echo "Holberton School" > /var/www/html/index.html

sed -i "/server_name _;/a \
    location /redirect_me {\
        return 301 https://www.google.com/;\
    }" /etc/nginx/sites-available/default

service nginx restart
