#!/usr/bin/env bash
# Configures custom 404 page with a custom string
set -e

apt-get update
apt-get install -y nginx

echo 'Holberton School for the win!' > /var/www/html/index.html

# Custom 404 page
cat > /var/www/html/404.html << 'EOF'
Ceci n'est pas une page</h1>

EOF


cat > /etc/nginx/sites-available/default << 'EOF'
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    server_name _;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    error_page 404.html  /;
    location = /404.html  {
        internal;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
EOF

nginx -t
service nginx restart
